theme: jekyll-theme-minimal
title: Jonathan Airey
description: Software Engineer
logo: assets/profile.jpg
favicon: assets/favicon.ico
google_analytics: UA-130418517-1
repository: aireytech/aireytech.github.io
